### ISSUE TITLE
proposal: allow more flexible account hierarchies

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#124]
hw allows multiple keyrings, but there is no facility for managing this with the current client commands

I believe the following commands should have a keyring parameter, and possibly also a derivation path parameter, if we are allowing complicated wallets. otherwise derivation path is always going to be some default

Account commands:
  newacc    name                          Create a new account 
  newread   name pubkey                   Create a new read-only account 
  newms     name M N [pubkey...]          Create a new multisig account 
  newreadms name M N [pubkey...]          Create a new read-only ms account
  accounts                                List all accounts in a keyring

There is a potential name spacing issue if two keyrings can have accounts with same name.  If name conflicts are not allowed, the following commands are unchanged, I think.

  setgap    acc gap                       Set the address gap for an account
  account   acc                           Display an account by name
  addkeys   acc  {pubkey...}              Add pubkeys to a multisig account

If conflicts are allowed, there needs to be a way to resolve this, eg fully qualified account name becomes keyring name + account name.

This brings up an interesting question about how hw client should be used in the wild. 

I see these possiblities
-- single user 
-- trusted cabal of users
-- public utility model with hundreds or thousands of users who are unknown to each other.

The single user or trusted cabal case is currently well supported, I think.

The public utility, name space conflicts become a thing.

I think we are going to be in a single user or small cabal world for hw client, but just throwing this out in case anyone sees an issue with this.

**Comment by tphyahoo** [comment]
I was mulling above

"possibly also a derivation path parameter, if we are allowing complicated wallets. otherwise derivation path is always going to be some default"

bip32 has the interesting property that you can branch off accounts from any level.  So, one way of managing this complexity would be to create a default account, named "head" or '' (empty string) or something like that, on keyring creation.

Or make it explicit by changing

newkeyring  [mnemonic] [-k name]        Create a new keyring
to
newkeyring  [mnemonic] [-k name]  rootaccountname      Create a new keyring with a named root account

Then, 

newacc name Create a new account 
becomes
newacc keyringname parentaccountname name Create a new account 

and you can create bip32 hierarchies of arbitrary complexity

Maybe this is just giving the user freedom to shoot himself in the foot... I kind of like it though.

Thoughts?

**Comment by tphyahoo** [comment]
never mind, this is controlled with 

--keyring 

flag.

I'm leaving this open for now, in case my proposal for having more flexible hierarchies is liked.

If so, that should be its own feature request and this should be closed.

Otherwise this should just be closed.

**Comment by xenog** [comment]
According to #5, we should move away from holding keyring information at all on the “server”, and we could probably even move away from labeled accounts as well. If the client should handle private keys, outputs, etc, it is its responsibility to label things, knowing that we can always have a facility to store encrypted account/address/etc. labels on the server, eventually.

I don’t think it is a good idea to do arbitrary hierarchy support at the server side, but to move that complexity to the client. Since the client will be able to register an extended public key with the server and have the server track its addresses and transactions (according to discussion in #5), it makes sense that the client may decide which arbitrary derivations the server must track.

**Comment by tphyahoo** [comment]
I agree.  Maybe I wasn't clear.

All of what I wrote was meant to apply to the hw client only. I begin to consider the server in #122

**Comment by tphyahoo** [comment]
changed title to reflect the only possibly relevant novelty in this thread.

**Comment by xenog** [comment]
Cool, yes, maybe we should have a way for the client to create an account by specifying:

- if account is multisig (m of n):
  - how many keys (m)
  - how many signatures (n)
- key(s), which are either:
  - plain extended public key(s)
  - derivation path from a master key
  - a combination of both (only multisig)
- number of addresses to pre-generate (optional)
- date of key creation
- gap of addresses that should have not been used

This information can be relayed to a Haskoin server, then the server will generate addresses, and then scan the blockchain from the specified date for transactions, generating more addresses if required to honour gap. The rescan can be substituted for a full blockchain index in the future, for increased performance.

Optionally, to help in establishing multisig accounts, an account may be created on the server with an incomplete set of keys, in which case whoever knows one of the extended public keys used can add its own public key to the account, until all keys have been added. Linking each of these extended public keys with encrypted metadata that resides in the server and is accessible to all parties in the multisig account could be a good idea, and perhaps there are ways to do so by creative use of the elliptic curve public keys keys already available.

This preserves the KISS principle.

**Comment by tphyahoo** [comment]
I'm starting to agree that storing some metadata on server, such as account names, derivation hierarchies and the like, is a reasonable thing to do. Particularly it makes communicating about shared keys a lot more straightforward, as you say.

This raises the question, do you you have granular access on the metadata, or everyone can see everything, as long as they have auth on the server?

Everyone sees everything makes sense if this is shared viewing wallet for a small business, but not so much if it is "public utility" for caching mpubkeys, or a viewing wallet for an exchange or similar service.

So, you are considering the harder case, and what to encrypt and how to do it.

I think I agree with everything except

" an account may be created on the server with an incomplete set of keys, in which case whoever knows one of the extended public keys used can add its own public key to the account, until all keys have been added."

There's an easier way to do this.

Assume we have named accounts, with names mapped to xpubkey, as in my initial comment.

Creating a multisig account is then just instead of

    newreadms name M N [pubkey...]

we do

    newreadms name M N [accountname1, accountname2...]

the server creates the account using fresh addresses derived from the various mpubkeys.  The derivations are included in the metadata when queried by

    account acc Display an account by name

I think we can do all of this and keep mpubkeys secret by hiding them on queries, but I'm not sure if it's worth going through the effort of hiding mpubkeys from other users.

**Comment by tphyahoo** [comment]
So, to be clear, I am disagreeing with 

    "we could probably even move away from labeled accounts as well"

because I am hoping to convince you that account name labels on server make multisig account coordination much easier to wrangle.

Once we have have labeled accounts on server it seems we have paid most of the cost of having more elaborate account hierarchies, but I don't care so much about that, as a one layer deep hierarchy covers most important use cases.

**Comment by tphyahoo** [comment]
Sorry, I changed my mind again about storing metadata on server.  

If haskoin adopts bip45, hw clients can become deterministic multisig wallets simply by importing their cosigners extended purpose' public keys, once.

> This information can be relayed to a Haskoin server, then the server will generate addresses

Clients can generate addresses to watch deterministically and send this to the server, and then we don't need to be caching mpubkeys+gap limits either.  Just addresses.

**Comment by tphyahoo** [comment]
Besides serving as a basic spv client, the haskoin server could also serve as a rendezvous point for partially signed transactions.  It might be instructive to study how bip45-supporting

https://github.com/bitpay/bitcore-wallet-service

accomplishes this.

Bitcore wallet service would be analogous hw server here, and the copay wallet would be analogous to the hw client.

It's interesting to note, from Security Considerationsi n the above link, "Extended public keys are stored on BWS. This allows BWS to easily check wallet balance, send offline notifications to copayers, etc."

This is a design choice, not a requirement.

As I said in previous comment, we can move all logic to client, and keep xpubkeys completely off server.

**Comment by tphyahoo** [comment]
@xenoj, your last comment on this thread amounts to basically copying the bitcore wallet service model. (Are there any differences?)

That's not a bad thing, and I wouldn't argue too much if that's the direction you want to go.

I'm just pointing out that it's possible to go with a zero metadata on server model and still have deterministic multisig keys client side, which is a little bit more secure.

It's also possible that it's a common use case that clients *want* to share metadata, and aren't too concerned about leaking it in the event of a hack.

**Comment by xenog** [comment]
Hey @tphyahoo,

Then the Bitcore wallet service model is good and we should aim to go in that direction.

The thing about the metadata is that I love the cloud, I want you to tag an address here, and see it in your mobile wallet. If your HDD burns, your mnemonic should get you back in track without metadata loss.

Therefore a model in which you keep metadata encrypted and stored in the server is good. It makes clients more stateless.

I believe we are witnessing a fork moment. We are departing so much from the existing haskoin-wallet that we may just start a separate project using haskoin and haskoin-node libraries, and simplifying storage. I would tend to prefer memory-based blockchain headers, and LevelDB for transactions and addresses.

**Comment by tphyahoo** [comment]
I'm not so certain it's time to fork, but if you spin something up I'll probably go with the flow.

OK, so back to metadata on server.  I think this is a can of worms, so I will share some design considerations that will either scare you away from the worms, or otherwise clarify direction.

Design considerations... 

1 -- Zero Knowledge or server gets hacked means metadata gets leaked?

Bitpay has gone non-zero-knowledge with bws.  I'm assuming that is your model model as well.

Nice things about zero knowledge 
  -- it gets you granular permissioning for free. 
  -- one else seems to be doing it, so it would be a real differentiator if achieved

Bad thing about zero nowledge
  -- it's harder.   

2 -- Is metadata (and historical transaction data) available offline?  I guess we want some offline cache so this works ok.

3 -- CRUD, or WORM? I guess CRUD. I don't really see why user would want to delete a label, but since it's a deterministic wallet at least no value is lost this way.

4 -- do users want to share metadata (like account names for multisig accounts) with each other?  

OK, but now we need granular permissions with acls. Maybe each account gets an acl for who is allowed to read from it (or even know it exists). 

5 -- What if two authed user (or same user in different places) make conflicting updates?

**Comment by tphyahoo** [comment]
@xenog: this is either total overkill, or "cloud wallet done right."

proposal: zero knowledge account-pegged meta data storage with acls.

The basic idea is borrowed from the alt.anonymous.messages usenet community. On a.a.m, messages are world viewable, but postable/decryptable only if you have been accepted into the group (your pubkey is on the a.a.m ACL, which is a list of pgp pub keys).  Posters are responsible for encrypting data for every pub key.  Only messages with valid signatures are posted.

In our zero knowledge metadata wallet, metadata is updated by appending encrypted data to sqlite table. It is the client’s responsibility to encrypt the data for everyone on the acl list (just as with a.a.m.), since server doesn’t have priv keys.  To keep the appended encrypted data from growing forever, we implement a fixed size fifo buffer and drop old metadata updates after a while. Of course, we use signatures too, just like a.a.m.

(quasi humorous side note: maybe we should use a.a.m. for storing metadata. Or bitmessage! But we’re boring and we’re already using sqlite and this is fine too.)

We want to decouple metadata encrypting keys, from bitcoin controlling keys.  

I’m not sure the best way to do this, but two ideas are
  — use a completely different mechanism from bitcoin, like pgp or openssl
  — use bitcoin E.C. keys, but take care these don’t control any bitcoin (for instance, by reserving a deriv path that should ONLY be used for this purposes

I’ll defer further consideration of precise key mechanism for now. We’ll call these keys metadata keys, to differentiate them from bitcoin keys.

hw accounts have at least one acl, which controls who can read and write all metadata.  This can be made more granular by having separate acls depending on the metadata. EG, account metadata, versus multisig transaction proposal metadata. It’s easy to add more acls as use cases arise. For version one, I think one acl for everything suffices.  

  The acls are lists of pub keys. 

  modifying acl requires the xprivkey tied to the account. keys can be added or deleted.

  If you’re on the acl list, you can both read and write the channel, as with alt.messages.anonymous.

  the metadata that is stored is a json object containing account name, address labels for the account, and account history, with derived address and account labels where possible. This is stored encrypted with every pub key, in sqlite.

  We also store pending multisig transaction proposals here, for use as a convenient but protected rendezvous point for communicating multisig transactions.  

If a user’s wallet is destroyed, he can 
  — recover funds with seed (but without any labeling information)
  — recover metadata from any pgp priv key associated to the ACL
  — start writing metadata again by generating a new priv key and associating it to the acl
  — if there is no priv key for the stored encrypted data, he loses all the labels, but of course still has the coins

BTW, iiuc, bitcore wallet service does not keep metadata like labels on server.  There is an option to make backups in copay client.

So if implemented this feature would be unique to haskoin wallet.

**Comment by xenog** [comment]
Hey @tphyahoo,

Your ideas are not crazy at all, I have been thinking about using the blockchain itself to store account metadata.  We should use privacy-enhanced BIP-45 as I proposed on bitcoin-dev recently.

Cheers

**Comment by xenog** [comment]
Hi @tphyahoo,

Actually, I was thinking of a much simpler model, which requires no (proper) authentication, but that goes more or less in the same direction as you are heading there.

## Regular (Non-Multisig) Accounts

For this type of account, the solution would be trivial: metadata is encrypted with a hardened derivation from the master key that isn’t used for any other purpose.   The client stores this encryption key itself encrypted with a password using a symmetric encryption algorithm.  Clients store metadata against a particular extended public key and an optional derivation path.  Anyone that knows the extended public key can download the encrypted metadata.  To upload or delete metadata, it must be signed with the private key corresponding to the extended public key to which the metadata belongs.  No other type of authentication is required.

Good for:

- labeling accounts (xpubs)
- labeling addresses
- attaching arbitrary metadata to either

## Multisig Accounts

The scheme described for regular accounts is used, with the addition of a multisig encryption key.  This key is calculated using ECDH among all account root keys from cosigners.  Metadata is encrypted with this key and signed with the private key of the user that uploads it.  Only the original uploader can delete a piece of encrypted metadata.  Anyone with knowledge of any of the extended public keys that compose an account can download the encrypted account metadata.

Good for:

- sharing transaction propositions
- messaging cosigners
- shared labels for cosigner public keys
- shared labels for addresses

Since the regular scheme is also implemented, you can override a label for an extended public key or address in your own private view of the multisig account.

## Unencrypted Data

The server will store some data unencrypted for performance and account recovery:

- extended public keys
- a set of addresses generated from these keys
- basic multi-signature account data: extended public key set and number of required signatures

This data is indexed by extended public key, and knowledge of any of any of the extended public keys involved should allow retrieval of the rest of associated data.  This will allow a user to easily retrieve all information concerning multisig accounts, for example.

## Multi-Signature Oracles

An automated entity known as an oracle can become a participant on a multi-signature account for security purposes.  Its job is to sign transaction proposals automatically on behalf of the account owner after doing additional identity verification or velocity checks, for example.

**Comment by tphyahoo** [comment]
very nice. wish I had thought of that myself.

As a quick observation, I think it would be good to register a new bip purpose scheme following

https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki

for a new kind of wallet.  That is, a wallet containing keys for encrypting wallet metadata, but expressly not for storing bitcoin value.


So the derivation you propose would be

m / wallet_metadata_encryption_purpose_id / 0

if we think we will only ever need a single key for encrypting metadata, or if we need more keys that should be explained in the bip for "wallet metadata encryption" and we can bounce this around further.

Then 

-- we're guaranteed  we don't conflict with the main wallet, which iiuc is under m/44 and maybe m/45 if bip45 gets incorporated.
-- we're one step closer to some kind of unified format for wallet metadata which would make wallets interoperable... maybe we should also do a bip for that?
-- of course your main objective of having cloud wallets with nice privacy properties

question about

"The client stores this encryption key itself encrypted with a password using a symmetric encryption algorithm."

why?  And who stores it?  

If it's the original client, and he has the seed, and we're not talking about encrypting the seed, why are we worried about encrypting just the metadata viewing key?

And if it's someone with viewing privileges but without the privkey seed, sort of the same issue.

I guess what I'm getting at is I thought we're moving away from specifically encrypting anything and instead focusing on physical security (with multisig and/or hardware wallets for high value) so I'm not sure if there's anything special about this particular key that we are treating it differently by caring about encrypting it even symmetrically with a password.

**Comment by tphyahoo** [comment]
another sticking point for me, from the section on multisig accounts

"This key is calculated using ECDH among all account root keys from cosigners. "

Can you say more about this mechanism?

I had a glimpse at

https://en.wikipedia.org/wiki/Elliptic_curve_Diffie%E2%80%93Hellman

and it seems ECDH is good for establishing a shared key given two public keys, but I didn't see any mechanism for establishing a shared key among more than two participants.

Also the mechanism you propose uses xpub keys for authentication and xpriv keys for uploading and modifying data.

So the end goal of the shared key would be an xpubkey derived from a number of others in a deterministic way.

But I don't see that ECDH actually accomplishes that, that is, I don't think ECDH gets you something that actually looks like an xpubkey, does it?

Maybe just sort the multiple xpub keys and xor them in sorted order? 

Don't know enough about cryptography to say if that's a good or safe idea or not, but at least it yields an xpub key.

**Comment by xenog** [comment]
## Metadata Encryption Key

Metadata is encrypted with using an extended private key derived from the wallet’s master key.  On the server, associated with the corresponding extended public key is a bunch of encrypted metadata, including all extended public subkeys (accounts) belonging to the wallet, which themselves may be associated to additional encrypted metadata pertaining to each individual account and address under the wallet.

## Metadata Key Management Options

### No Local Metadata Key

The Metadata key is not stored locally at all. Since the key used to encrypt the metadata is derived from the seed, not storing this key is acceptable as long as the user still has the seed.

### Unencrypted Metadata Key

The metadata encryption extended key may be stored unencrypted.  This exposes wallet data to potential attackers that may gain access to the device where the metadata key is stored, provided this device is not already encrypted by other means.

### Metadata Passphrase

The metadata passphrase encrypts a local copy of the encryption extended private key.  The presence of this passphrase, assuming it is secure, makes it harder for an attacker with access to the user’s disk to learn anything about the wallet.

## Seed Encryption Options

### No Seed

The user may decide not to store the wallet seed locally at all.

### Seed Passphrase

The seed of the wallet itself may be stored encrypted with a chosen passphrase locally on the client.  This passphrase would be required to send funds.

### Seed Encrypted by Hardware

A hardware encryption device may be used and the encrypted seed then stored locally.  In order to load the key in memory and use it to sign transactions, the hardware encryption device must be inserted.  Smart cards or possibly USB tokens can be used for this purpose.

### Seed Stored in Hardware

The seed can be stored in hardware that can calculate BIP-32 derivations and sign transactions. The device should be capable of exposing the encryption extended private key, or this key must be derived and stored locally at some point before uploading the seed or master key to the hardware device and erasing it from memory.

I will respond to your other queries tomorrow.

**Comment by tphyahoo** [comment]
from the oracle section

"Its job is to sign transaction proposals automatically on behalf of the account owner after doing additional identity verification or velocity checks, for example."

There are many potential cosigning scenarios. I don't see any reason to particularly elevate this one over many others.

Also oracle seems like the wrong word to me, unless you want to generically call almost any cosigner an oracle.

The right word here would be "banker" if retail banks provided such a service for bitcoin holders, or "crypto security nanny" perhaps.  (Maybe we need to invent a word.  Wallet buddy?)

I would either leave this section off the proposed bip entirely, or stick it in an appendix or a section "example applications" or something like that.

**Comment by tphyahoo** [comment]
I'd now like to rant a bit about

Metadata Key Management Options / Seed Encryption Options

This gets a bit opinionated.  But it's an opinion based on having done consulting for "civilians" with high value wallets, helping them get their brains around wallet security implications.  It's hard, because it's an unfamiliar and hostile domain -- by some counts, 10% of bitcoin is lost or stolen.  Too little security and you get hacked, too much security and you lock yourself out. So it's tricky.

I've found the following basic prescriptions to be invaluable in orienting users to a reality based mindset

1 -- physical access equals root
2 -- computer was ever connected to the internet, almost equals root

It's not about being draconian.  It's about making simplifying assumptions so that you can make good choices with confidence, and not bog down in paranoia about zero day attacks.

So rather than think about whether the password can be sniffed (it can), you focus on physical security, because that's easy to understand.  

Hardware wallets represent physical security.  They're a little portable zone of safety that doesn't leak privkeys.  "cold" computers, locked in a safe, are a kludge to accomplish the same thing.  (My view is that we basically should be shifting to ubiquitous hardware wallets, and hopefully this will happen soon.)

Anyway, with this view, the three "Metadata Key Management Options" presented boil down to the same thing.  All three leak metadata privkeys in the event that an attacker has bugged the computer.

-- No Local Metadata Key: leaked when the user enters the seed at the prompt
-- Unencrypted Metadata Key: self explanatory 
-- Metadata Passphrase: sniffed from ram after the user enters the passphrase

Passing on to the four seed encryption options

-- No seed: leaked at prompt
-- Passphrase: leaked after user enters passphrase
-- Encrypted by Hardware: leaked decryption 
-- Stored in Hardware: the only actually safe option, if the computer is bugged!

So far, we have the usual solution for securing the seed (hardware wallet), but funny enough we actually have no solution that does not leak the metadata privkey in the event of an attack!

I believe we can fix this by adding option 4 to Metadata Key Management Options

-- Stored in Hardware.  A trezor/ledger/etc.

People normally use trezor for signing transactions, but you can also use trezor to sign/decrypt arbitrary data.

See 

https://github.com/hiviah/TrezorPass/

for an example of this in action.

My recommendation is to deprecate passpharase and seed encrypted by hardware options, and direct user either to 
  -- be cavalier about security for low value wallets, and keep the seed phrase in a config file or entered at the prompt
  -- use hardware wallet or cold computer if the metadata is high value.  (Just like if the bitcoin is high value.)

I think passphrase and hardware element solutions, that leak privkeys to ram, are just going to give users a false sense of security and/or confuse them about where privkeys actually live.

The principle that privkeys never cross a certain boundary is VERY important, and symmetric encryption and vanilla hardware encryption (but not trezor) violate this.

**Comment by tphyahoo** [comment]
re 

-- labeling addresses

I think it's in poor taste to label individual bitcoin addresses in the wallet metadata.

I think it will be easier to build, maintain, and (hopefully someday) interoperate an ecosystem of metadata compatible wallets if we always label the xpubkey, and pretty much treat addresses as derived data.

**Comment by xenog** [comment]
Hey @tphyahoo,

Oracle refers to an automated signer, as opposed to a human being.  Therefore in an escrow arrangement between a buyer and seller there will usually not be any oracles, but in a security provider arrangement where a machine is validating one-time-passwords and velocity checks, there will.  I think the term may have been coined by Nick Szabo.  I read it first [here](https://en.bitcoin.it/wiki/Contract#Example_4:_Using_external_state).

Labeling addresses is useful to monitor incoming payments.  If you are meant to use an address only once, then labeling addresses is like labeling expected transactions, which is useful.  Most users will have a single account.  By the way, transactions should also be able to get labels, keyed to the extended public key public and transaction id (or better: transaction hash excluding signatures).  For multisig, they should be keyed by all xpubs and transaction id.

About your rant.  I agree with your security assessment, but I prefer to have practical security instead of extreme security that may or may not be practical for everybody.

Although Trezor seems to be selling for about US$ 130 in some places, many users only have that much in Bitcoin.  They will not pay US$ 130 to protect that amount or less.  It is unreasonable, so a solution without Trezor is necessary.

Defending against a compromised client system is nigh impossible.  Assume you have Trezor, and you have a bugged computer, and you’re buying something online and doing a payment, malware can alter the bitcoin address of your payee on screen, and that means that the Trezor will get the wrong address too.  Both will match, you’ll accept to pay on the Trezor, and you’ll have been robbed.  Working with the assumption of an attacker having full control of the client system is hard.  One possible solution for this scenario by the way involves multisig and MePIN, which pops a notification on your smartphone showing the actual address and amount that the transaction goes to for signing on another system.  Of course we can always say that the smartphone may be compromised *too*, and that is not trustworthy anymore.  It is turtles all the way down.

For advanced users we should offer choice.  For novices we should have default security settings.  Something like multisig oracle + MePIN can work.  Something like Trezor can work (although payments won’t be possible from a mobile phone.  Other choices can work too.  I want to set the basis of multiple security arrangements that we can experiment with.

Do not forget that the most popular Bitcoin wallet out there is Blockchain.info.  Their security model assumes that the client is not compromised, and so far that has worked, with some reported cases of lost funds, but most users managing to hold on to their coins.  Security is important, and operating system writers, web browser writers, and application writers are understanding this.  Things have improved from the days of Blaster.  But we still need to constantly manage tradeoffs between security and convenience.  Forcing everyone to use a Trezor or similar device will harm the convenience side of things (no mobile), and as I demonstrated it does not completely guarantee that it will resist all possible attacks.  So, security is improving, but there are still no silver bullets.  There is more than one way to do it.

Cheers!

**Comment by xenog** [comment]
This discussion should be started again in the repository if necessary.
