### ISSUE TITLE
zero knowledge metadata storage 

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#128]
this is a placeholder to focus conversation currently taking place on #124 and maybe some other places

this encompasses both single signer and multisig scenarios.

if we can make single signer accounts a degenerate case of multisigner accounts first, before tackling this, this task might be easier.

**Comment by tphyahoo** [comment]
Seems like satoshi labs might be interested in commenting or helping spec some of this. See stubs for slip-0011, slip-0012, and fleshed out slip-0013 

http://doc.satoshilabs.com/slips/

**Comment by tphyahoo** [comment]
Have you considered tarsnap integration?

https://www.tarsnap.com/download/EuroBSDCon13.pdf

Tarsnap is
-- built on aws/s3
-- pretty cheap (double s3 per gb, but you make it up by having efficient diffs)
-- efficient with deltas (rather than redundant back up everything everything)
-- zero knowledge
-- accepts bitcoin
-- respected member of security community (cpercival)
-- client is open source: https://www.tarsnap.com/download.html encryption can be audited 
-- seems likely to be around for a long time (profitable, low key, streamlined)
-- has user friendly permissioning: read and write keys, and keys can be password protected like with ssh

The end game here would be that if a wallet metadata cloud storage server got blown away, it could restore everything from backups with just a tarsnap key.  Costs could be passed on to users via bitcoin payment.  Or costs might be small enough to be just noise, depending on volume and what we're storing

**Comment by xenog** [comment]
It is an option, I haven't thought about it. What I have considered is some kind of metadata storage system that is blockchain-storage friendly, meaning that it could end up stored in data transaction outputs as well as on a server's disk. Right now the size of allowed data outputs is a bit small (80 bytes), so that storing some metadata in transaction outputs might be a bit expensive for some (most?) users, but even then some metadata could still make sense there, especially things that are not possible to easily infer by looking at only transactions, such as the configuration of a multisig account. For this a custom mechanism is probably in order.

**Comment by tphyahoo** [comment]
I think someone already said this in a different issue thread but storing data on the blockchain is probably not the way to go. expensive now, and if bitcoin is on success oath will be much much more expensive in future.

blockchain is for recording high value contracts, not labeling information.

**Comment by xenog** [comment]
Yeah, perhaps you are right.

**Comment by xenog** [comment]
We should continue this discussion in the new repository if necessary.
